version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=admin
    volumes:
        - /db/mysql:/var/lib/mysql     
  php-fpm7.4:
    build:
      context: ./php-fpm7.4
    image: inovationzone/php-fpm7.4
    container_name: php-fpm7.4
    volumes:
      - /www:/var/www/   
  nginx:
    build:
      context: ./nginx
    image: inovationzone/nginx
    container_name: nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - /www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - /var/log/nginx-error.log:/var/log/nginx/error.log
      - /var/log/nginx-access.log:/var/log/nginx/access.log
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on: 
      - mysql
    links: 
      - mysql
    ports:
      - 8183:80
    environment: 
      PMA_HOST: mysql
      PMA_ROOT_PASSWORD: admin

  
      

